/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#e1e0ff",
        "on-surface-variant": "#454652",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#c0c1ff",
        "tertiary-fixed": "#e4dfff",
        "surface": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "secondary": "#00677f",
        "on-primary": "#ffffff",
        "inverse-surface": "#2d3133",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#04006d",
        "tertiary-fixed-dim": "#c5c0ff",
        "outline": "#757684",
        "surface-container-low": "#f2f4f6",
        "surface-container-high": "#e6e8ea",
        "tertiary": "#3925b5",
        "secondary-container": "#00d2ff",
        "surface-variant": "#e0e3e5",
        "on-background": "#191c1e",
        "on-tertiary-fixed": "#140067",
        "surface-container": "#eceef0",
        "on-primary-container": "#ceceff",
        "inverse-on-surface": "#eff1f3",
        "tertiary-container": "#5243cd",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#c0c1ff",
        "on-primary-fixed-variant": "#373a9b",
        "secondary-fixed": "#b6ebff",
        "surface-tint": "#4f54b4",
        "on-secondary-fixed-variant": "#004e60",
        "on-tertiary-fixed-variant": "#3d2bb9",
        "primary-container": "#4b4fb0",
        "on-secondary-container": "#00566a",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e0e3e5",
        "background": "#f7f9fb",
        "surface-bright": "#f7f9fb",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#001f28",
        "primary": "#333697",
        "outline-variant": "#c5c5d4",
        "on-error": "#ffffff",
        "on-tertiary-container": "#d2ccff",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#191c1e",
        "secondary-fixed-dim": "#47d6ff"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
