// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prefer an explicit direct URL for Supabase migrations, otherwise fall back to the runtime DATABASE_URL.
    url: process.env["DIRECT_DATABASE_URL"]
      || process.env["SUPABASE_DIRECT_URL"]
      || process.env["DATABASE_URL"]?.replace(':6543', ':5432'),
  },
});
