// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Force direct connection for migrations if using Supabase pooler (6543 -> 5432)
    url: process.env["DATABASE_URL"]?.replace(':6543', ':5432'),
  },
});
