// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prefer the unified APP_* direct URL, then planner legacy names, then derive from runtime.
    url: process.env["APP_DIRECT_DATABASE_URL"]
      || process.env["DIRECT_DATABASE_URL"]
      || process.env["SUPABASE_DIRECT_URL"]
      || process.env["APP_DATABASE_URL"]?.replace(':6543', ':5432')
      || process.env["DATABASE_URL"]?.replace(':6543', ':5432'),
  },
});
